name: sih_shetkari
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BLOCKCHAIN
  web3dart: ^2.7.3
  walletconnect_flutter_v2: ^2.0.14
  http: ^1.1.0   # required by cloudinary

  # UI + Firebase + Others
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  crypto: ^3.0.6

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  provider: ^6.1.2
  shared_preferences: ^2.3.3

  flutter_tts: ^4.2.3

  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.6.0

  flutter_dotenv: ^5.2.1
  highlight_text: ^1.8.0
  avatar_glow: ^3.0.1
  file_picker: ^8.1.4
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/ImageIntegrity.json
    - .env

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic
        - asset: assets/fonts/Merriweather-Bold.ttf
    - family: Mergeone
      fonts:
        - asset: assets/fonts/MergeOne-Regular.ttf